#!/usr/bin/env bash
# Regenerate the skills TOC in README-skills.md and the cross-link block in
# the overview skill's SKILL.md from the current skills/* directories.
#
# Idempotent: running twice produces bit-identical output (alphabetical sort,
# no timestamps, no random IDs).
# D-19 invariant: skill names are discovered via skills/*/ glob, never hardcoded.
# Exit 0 on success, 1 on write failure.
set -euo pipefail

build_table() {
  for dir in skills/*/; do
    [ -f "$dir/SKILL.md" ] || continue
    name=$(basename "$dir")
    desc=$(awk '
      /^---$/{c++; next}
      c==1 && /^description:/{sub(/^description:[[:space:]]*/,""); print; exit}
    ' "$dir/SKILL.md")
    printf '| %s | %s |\n' "$name" "$desc"
  done | sort
}

build_links() {
  for dir in skills/*/; do
    [ -f "$dir/SKILL.md" ] || continue
    name=$(basename "$dir")
    printf -- '- [%s](../%s/SKILL.md) — see the %s skill\n' "$name" "$name" "$name"
  done | sort
}

rewrite_markers() {
  local file="$1" start="$2" end="$3" body="$4"
  [ -f "$file" ] || { echo "skip: $file not found"; return 0; }
  local tmp
  tmp=$(mktemp)
  awk -v start="$start" -v end="$end" -v body="$body" '
    $0 ~ start { print; print body; skip=1; next }
    $0 ~ end   { skip=0; print; next }
    !skip      { print }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

TABLE_BODY=$'<!-- DO NOT EDIT \xe2\x80\x94 regenerated by scripts/generate-readme-toc.sh -->\n| Skill | Description |\n|-------|-------------|\n'"$(build_table)"
LINKS_BODY=$'<!-- DO NOT EDIT \xe2\x80\x94 regenerated by scripts/generate-readme-toc.sh -->\n'"$(build_links)"

# README-skills.md is the staging filename (plan 11 renames to README.md)
rewrite_markers "README-skills.md"                    "SKILLS_TOC_START"   "SKILLS_TOC_END"   "$TABLE_BODY"
rewrite_markers "skills/floless-overview/SKILL.md"    "SKILLS_LINKS_START" "SKILLS_LINKS_END" "$LINKS_BODY"

echo "regenerated README-skills.md + overview cross-link block (if present)"
